openapi: 3.0.0
info:
  title: Ebsconet integration API
  description: "Ebsconet integration API"
  version: 0.0.1
servers:
  - url: /ebsconet/
paths:
  /orders/order-lines/{poLineNumber}:
    get:
      summary: Get single Ebsconet product order line
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ebsconetOrderLine"
        '400':
          description:
            Bad request, e.g. malformed request body or query parameter.
            Details of the error (e.g. name of the parameter or line/character number
            with malformed data) provided in the response.
          content:
            application/json:
              example:
                $ref: "#/components/examples/error"
              schema:
                $ref: "#/components/schemas/error"
        '404':
          description: Purchase order line with a given number not found
          content:
            application/json:
              example:
                $ref: "#/components/examples/error"
              schema:
                $ref: "#/components/schemas/error"
        '500':
          description: Internal server error, e.g. due to misconfiguration
          content:
            application/json:
              example:
                $ref: "#/components/examples/error"
              schema:
                $ref: "#/components/schemas/error"
      operationId: getEbsconetOrderLine
      parameters:
        - name: poLineNumber
          in: path
          description: product order line number
          required: true
          schema:
            $ref: "#/components/schemas/poLineNumber"
    put:
      summary: Save single Ebsconet product order line
      responses:
        '200':
          description: OK
        '400':
          description:
            Bad request, e.g. malformed request body or query parameter.
            Details of the error (e.g. name of the parameter or line/character number
            with malformed data) provided in the response.
          content:
            application/json:
              example:
                $ref: "#/components/examples/error"
              schema:
                $ref: "#/components/schemas/error"
        '500':
          description: Internal server error, e.g. due to misconfiguration
          content:
            application/json:
              example:
                $ref: "#/components/examples/error"
              schema:
                $ref: "#/components/schemas/error"
      operationId: putEbsconetOrderLine
      parameters:
        - name: poLineNumber
          in: path
          description: product order line number
          required: true
          schema:
            $ref: "#/components/schemas/poLineNumber"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ebsconetOrderLine"
        required: true
components:
  schemas:
    ebsconetOrderLine:
      $ref: schemas/ebsconet_order_line.json
    poLineNumber:
      $ref: schemas/order_line_number.json
    error:
      $ref: schemas/common/error.json#/Error
  examples:
    error:
      value:
        $ref: examples/error.sample
